// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViajaMaisAPI.Data;

#nullable disable

namespace ViajaMaisAPI.Migrations
{
    [DbContext(typeof(ViajaMaisContext))]
    partial class ViajaMaisContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("ViajaMaisAPI.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCadastro = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Documento = "111.222.333-44",
                            Email = "ana@email.com",
                            Nome = "Ana Paula",
                            Telefone = "14999990001"
                        },
                        new
                        {
                            Id = 2,
                            DataCadastro = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Documento = "555.666.777-88",
                            Email = "bruno@email.com",
                            Nome = "Bruno Costa",
                            Telefone = "14999990002"
                        });
                });

            modelBuilder.Entity("ViajaMaisAPI.Models.Destino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoOuPais")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Destinos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cidade = "Rio de Janeiro",
                            Descricao = "A Cidade Maravilhosa com suas praias icônicas e o Cristo Redentor.",
                            EstadoOuPais = "RJ"
                        },
                        new
                        {
                            Id = 2,
                            Cidade = "Gramado",
                            Descricao = "Charme europeu, arquitetura alpina e a famosa Rota do Chocolate.",
                            EstadoOuPais = "RS"
                        });
                });

            modelBuilder.Entity("ViajaMaisAPI.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Classificacao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DestinoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoDiaria")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DestinoId");

                    b.ToTable("Hoteis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Classificacao = 0,
                            DestinoId = 1,
                            Endereco = "Av. Atlântica, 1702",
                            Nome = "Copacabana Palace",
                            PrecoDiaria = 0m
                        },
                        new
                        {
                            Id = 2,
                            Classificacao = 0,
                            DestinoId = 2,
                            Endereco = "Rua Leopoldo Rosenfeld, 67",
                            Nome = "Hotel Alpestre",
                            PrecoDiaria = 0m
                        });
                });

            modelBuilder.Entity("ViajaMaisAPI.Models.PacoteViagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataRetorno")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataSaida")
                        .HasColumnType("TEXT");

                    b.Property<int>("DestinoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomePacote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("VagasDisponiveis")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DestinoId");

                    b.ToTable("PacotesViagem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataRetorno = new DateTime(2026, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataSaida = new DateTime(2026, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinoId = 1,
                            NomePacote = "Férias no Rio de Janeiro",
                            Preco = 1850.00m,
                            VagasDisponiveis = 20
                        },
                        new
                        {
                            Id = 2,
                            DataRetorno = new DateTime(2026, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataSaida = new DateTime(2026, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinoId = 2,
                            NomePacote = "Natal Luz em Gramado",
                            Preco = 2490.90m,
                            VagasDisponiveis = 15
                        });
                });

            modelBuilder.Entity("ViajaMaisAPI.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("TEXT");

                    b.Property<int>("PacoteViagemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadePassageiros")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusPagamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PacoteViagemId");

                    b.ToTable("Reservas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 1,
                            DataCompra = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PacoteViagemId = 1,
                            QuantidadePassageiros = 2,
                            StatusPagamento = "Confirmado"
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 2,
                            DataCompra = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PacoteViagemId = 2,
                            QuantidadePassageiros = 1,
                            StatusPagamento = "Pendente"
                        });
                });

            modelBuilder.Entity("ViajaMaisAPI.Models.Hotel", b =>
                {
                    b.HasOne("ViajaMaisAPI.Models.Destino", "Destino")
                        .WithMany("Hoteis")
                        .HasForeignKey("DestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destino");
                });

            modelBuilder.Entity("ViajaMaisAPI.Models.PacoteViagem", b =>
                {
                    b.HasOne("ViajaMaisAPI.Models.Destino", "Destino")
                        .WithMany("PacotesViagem")
                        .HasForeignKey("DestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destino");
                });

            modelBuilder.Entity("ViajaMaisAPI.Models.Reserva", b =>
                {
                    b.HasOne("ViajaMaisAPI.Models.Cliente", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViajaMaisAPI.Models.PacoteViagem", "PacoteViagem")
                        .WithMany("Reservas")
                        .HasForeignKey("PacoteViagemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("PacoteViagem");
                });

            modelBuilder.Entity("ViajaMaisAPI.Models.Cliente", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ViajaMaisAPI.Models.Destino", b =>
                {
                    b.Navigation("Hoteis");

                    b.Navigation("PacotesViagem");
                });

            modelBuilder.Entity("ViajaMaisAPI.Models.PacoteViagem", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
